app/posts/models.py
from datetime import datetime
from app import db
from sqlalchemy import Enum

post_tag = db.Table('post_tag',
    db.Column('post_id', db.Integer, db.ForeignKey('post.id')),
    db.Column('tag_id', db.Integer, db.ForeignKey('tag.id'))
)

class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(255), nullable=False)
    text = db.Column(db.String, nullable=False)
    image_file = db.Column(db.String, default='postdefault.jpg')
    created = db.Column(db.TIMESTAMP, default=datetime.now)
    type = db.Column(db.Enum('news', 'publication', 'other'), default='other')
    enabled = db.Column(db.Boolean, default=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)

    category_id = db.Column(db.Integer, db.ForeignKey('category.id'))
    category = db.relationship('Category', backref=db.backref('posts', uselist=False))
    tags = db.relationship('Tag', secondary=post_tag, backref=db.backref('posts', lazy=True))


    def __repr__(self):
        return f"Post {self.id}: {self.title}."
        

class Category(db.Model):

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String)

    def __repr__(self):
        return f"Category {self.id}: {self.name}."


class Tag(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String)

    def __repr__(self):
        return f"Tag {self.id}: {self.name}."

app/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, SelectField, FileField
from wtforms.validators import DataRequired, Length, Email, EqualTo, Regexp
from flask_wtf.file import FileAllowed


class CreatePost(FlaskForm):
    title = StringField('Title:',
                        validators=[DataRequired("This field is required.")],
                        render_kw={"class": "form-control"})
    text = TextAreaField('Write your post:', 
                         validators=[DataRequired("This field is required.")],
                         render_kw={"class": "form-control"})
    type = SelectField("Post type:", 
                       validators=[DataRequired("Select a type.")],
                       choices=[("news", "News"), ("publication", "Publication"), ("other", "Other")],
                       render_kw={"class": "form-control", "multiple": True})
    category = SelectField('Post category', 
                           validators=[DataRequired("Select a type.")],
                           render_kw={"class": "form-control", "multiple": True})
    image_file = FileField('Add image:', 
                           validators=[FileAllowed(['jpg', 'png'])],
                           render_kw={"class": "form-control"})
    submit = SubmitField('Create',
                         render_kw={"class": "btn btn-primary"})  
    

class EditPostForm(FlaskForm):
    title = StringField('Title:',
                        validators=[DataRequired("This field is required.")],
                        render_kw={"class": "form-control"})
    text = TextAreaField('Write your post:', 
                         validators=[DataRequired("This field is required.")],
                         render_kw={"class": "form-control"})
    type = SelectField("Post type:", 
                       validators=[DataRequired("Select a type.")],
                       choices=[("news", "News"), ("publication", "Publication"), ("other", "Other")],
                       render_kw={"class": "form-control", "multiple": True})
    category = SelectField('Post category', 
                           validators=[DataRequired("Select a type.")],
                           render_kw={"class": "form-control", "multiple": True})
    image_file = FileField('Change image:', 
                           validators=[FileAllowed(['jpg', 'png'])],
                           render_kw={"class": "form-control"})
    submit = SubmitField('Submit',
                         render_kw={"class": "btn btn-primary"})  


class CreateCategory(FlaskForm):
    name = StringField('Name:',
                        validators=[DataRequired("This field is required.")],
                        render_kw={"class": "form-control"})
    submit = SubmitField('Create',
                         render_kw={"class": "btn btn-primary"})

app/posts/__init__.py
from flask import Blueprint

posts = Blueprint('posts', __name__, template_folder="templates/posts")

from . import views

app/posts/views.py
from flask import flash, redirect, render_template, url_for, make_response, request
from flask_login import current_user, login_required

from app import db
from .models import Post
from .models import Category

from .forms import CreatePost
from .forms import EditPostForm
from .forms import CreateCategory

from .saver import save_picture

from . import posts


@posts.route("/create", methods=['GET', 'POST'])
@login_required
def create():
    form = CreatePost()

    form.category.choices = [(category.id, category.name) for category in Category.query.all()]

    image_file = None

    if form.validate_on_submit():
        title = form.title.data
        text = form.text.data
        type = form.type.data
        category = Category.query.get(form.category.data)
        user_id = current_user.id

        if form.image_file.data:
            image_file = save_picture(form.image_file.data)

        post = Post(title=title, text=text, image_file=image_file, type=type, category=category, user_id=user_id)

        db.session.add(post)
        db.session.commit()

        flash('Your post has been created!', 'success')
        return redirect(url_for('posts.create'))

    return render_template('new_post.html', form=form)



@posts.route('/post', methods=['GET'])
def all_posts():
    posts = Post.query.filter_by(enabled=True).all()

    return render_template('all_posts.html', posts=posts)


@posts.route("/post/<int:id>")
def post(id):
    post = Post.query.filter_by(id=id).first_or_404()

    return render_template("post.html", post=post, current_user=current_user)


@posts.route("/post/<int:id>/edit", methods=['GET', 'POST'])
def edit(id):
    post = Post.query.get_or_404(id)
    form = EditPostForm() 

    form.category.choices = [(category.id, category.name) for category in Category.query.all()]

    if form.validate_on_submit():
        if form.title.data != post.title or form.text.data != post.text or form.type.data != post.type or form.category.data != post.category:
            post.title = form.title.data
            post.text = form.text.data
            post.type = form.type.data
            post.category = Category.query.get(form.category.data)
            db.session.commit()

            flash("Post has been updated", "success")
            return redirect(url_for('posts.post', id=post.id))
        
        if form.image_file.data:
            post.image_file = save_picture(form.image_file.data)
            db.session.commit()

            flash("Post has been updated", "success")
            return redirect(url_for('posts.post', id=post.id))
        
        else:
            flash('No changes were made to your post.', 'info')
            return redirect(url_for('posts.post', id=post.id))

    elif request.method == 'GET':
        form.title.data = post.title
        form.text.data = post.text
        form.type.data = post.type
        form.category.data = post.category

    return render_template('edit.html', post=post, form=form)


@posts.route("/post/<int:id>/delete")
def delete(id):
    post = Post.query.filter_by(id=id).first_or_404()
        
    db.session.delete(post)
    db.session.commit()
    flash("Post has been deleted", "success")
    return redirect(url_for('posts.all_posts'))


@posts.route('/categories', methods=['GET', 'POST'])
def categories():
    form = CreateCategory()
    
    if form.validate_on_submit():
        print(form.name.data)
        name = form.name.data
        new_category = Category(name=name)
    
        db.session.add(new_category)
        db.session.commit()
        flash('New category added successfully', 'success')
        return redirect(url_for("posts.categories"))
            
    categories = Category.query.all()

    return render_template('categories.html', form=form, categories=categories)


@posts.route('/categories/<int:id>/delete')
def delete_category(id):
    category = Category.query.filter_by(id=id).first_or_404()

    db.session.delete(category)
    db.session.commit()
    flash("Category has been deleted", "success")
    return redirect(url_for('posts.categories'))

app/posts/templates/posts/all_posts.html
{% from 'render_field.html' import render_field %}
{% extends "base.html" %}

{% block title %} Users {% endblock %}

{% block content %}

<h1>Posts page</h1>
<br>
<div>
    <div class="mt-4">
        <table class="table mb-4 text-center">
            <thead>
                <tr>
                    <th scope="col">Id</th>
                    <th scope="col">Title</th>
                    <th scope="col">Image</th>
                    <th scope="col">Text</th>
                    <th scope="col">Type</th>
                    <th scope="col">Category</th>
                    <th scope="col">Date</th>
                </tr>
            </thead>
            <tbody style="vertical-align: middle;">
                {% for post in posts %}
                <tr>
                    <td>
                        {{ post.id }}</a>
                    </td>
                    <td>
                        <a href="{{ url_for('posts.post', id=post.id) }}">{{ post.title }}</a>
                    </td>
   
                    <td>
                        <img alt="..." class="img-fluid rounded shadow-lg" src="{{ url_for('static', filename='images/' + post.image_file) }}" style="width: 150px; height: 150px;">
                    </td>

                    <td>
                        {{ post.text[:33] }}{% if post.text|length > 0 %}...{% endif %}
                    </td>

                    <td> 
                        {{post.type}}
                    </td>

                    <td> 
                        <span class="badge rounded-pill bg-primary">{{post.category.name}}</span>
                    </td>

                    <td> 
                        {{post.created.strftime('%Y-%m-%d %H:%M:%S')}}
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>        
    </div>
</div>

{% endblock %}

app/posts/templates/posts/categories.html
{% from 'render_field.html' import render_field %}
{% extends "base.html" %}

{% block title %} Users {% endblock %}

{% block content %}

<h1>Categories page</h1>
<br>
<div>
    <div class="mt-4">
        <table class="table mb-4 text-center">
            <thead>
                <tr>
                    <th scope="col">Id</th>
                    <th scope="col">Name</th>
                    <th scope="col">Edit</th>
                    <th scope="col">Delete</th>
                </tr>
            </thead>
            <tbody style="vertical-align: middle;">
                {% for category in categories %}
                <tr>
                    <td>
                        {{ category.id }}
                    </td>
                    <td>
                        {{ category.name }}
                    </td>
                    <td>
                        <a class="btn btn-primary btn-sm">Edit</a>
                    </td>
                    <td> 
                        <a class="btn btn-danger btn-sm" href="{{ url_for('posts.delete_category', id=category.id) }}">Delete</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>        
    </div>
</div>

<h1>New category</h1>

<div class="d-flex justify-content-center align-items-center">
    <div class="mt-4 col-sm-3">
        <form action={{url_for("posts.categories")}}  method="POST" novalidate enctype="multipart/form-data">
            {{ form.csrf_token }}
            {{ render_field(form.name)}}
            <br>
            <div class="button-container d-grid"> 
                {{form.submit()}}
            </div>
        </form>
    </div>
</div>

{% endblock %}

app/posts/templates/posts/edit.html
{% from 'render_field.html' import render_field %}
{% extends "base.html" %}

{% block title %} Account {% endblock %}

{% block content %}

<h1>Edit post page</h1>

<div class="d-flex justify-content-center align-items-center">
    <div class="mt-4 col-sm-5">
        <p>Post image:</p>
        <img src="{{ url_for('static', filename='images/' + post.image_file) }}" alt="Post Image" style="width: 100%;">
    </div>
</div>
<div class="d-flex justify-content-center align-items-center">
    <div class="mt-4 col-sm-5">
        <form action="{{ url_for('posts.edit', id=post.id) }}" method="POST" novalidate enctype="multipart/form-data">
            {{ form.csrf_token }}
            {{ render_field(form.title) }}
            {{ render_field(form.text) }}
            {{ render_field(form.type) }}
            {{ render_field(form.category)}}
            {{ render_field(form.image_file) }}
            <br>
            <div class="button-container d-grid">
                {{ form.submit() }}
            </div>
        </form>
    </div>
</div>
<br>
<br>

{% endblock %}

app/posts/templates/posts/new_post.html
{% from 'render_field.html' import render_field %}
{% extends "base.html" %}

{% block title %} Account {% endblock %}

{% block content %}


<h1>New post page</h1>


<div class="d-flex justify-content-center align-items-center">
    <div class="mt-4 col-sm-3">
        <form action={{url_for("posts.create")}}  method="POST" novalidate enctype="multipart/form-data">
            {{ form.csrf_token }}
            {{ render_field(form.title)}}
            {{ render_field(form.text)}}
            {{ render_field(form.type)}}
            {{ render_field(form.category)}}
            {{ render_field(form.image_file) }}
            <br>
            <div class="button-container d-grid"> 
                {{form.submit()}}
            </div>
        </form>
    </div>
</div>
<br>
<br>
{% endblock %}

app/posts/templates/posts/post.html
{% from 'render_field.html' import render_field %}
{% extends "base.html" %}

{% block title %} Users {% endblock %}

{% block content %}

<div class="card mt-4 mx-auto" style="width: 50%;">
    <div class="card-body">
        <div class="d-flex justify-content-between align-items-center mb-3">
            <h1 class="card-title">{{ post.title }}</h1>
            {% if current_user.is_authenticated %}
                <div>
                    <a class="btn btn-primary btn-sm" href="{{ url_for('posts.edit', id=post.id) }}">Edit</a>
                    <a class="btn btn-danger btn-sm" data-bs-toggle="modal" data-bs-target="#deleteModal">Delete</a>

                    <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                          <div class="modal-content">
                            <div class="modal-header">
                              <h5 class="modal-title" id="deleteModalLabel">Delete</h5>
                              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true"></span>
                              </button>
                            </div>
                            <div class="modal-body">
                              <p>Do you really want to delete this post?</p>
                            </div>
                            <div class="modal-footer">
                                <a class="btn btn-primary" href="{{ url_for('posts.delete', id=post.id) }}">Delete</a>
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                            </div>
                          </div>
                        </div>
                      </div>
                </div>
            {% endif %}
        </div>

        <div class="text-muted small mb-2">
            Posted on {{ post.created.strftime('%Y-%m-%d %H:%M:%S') }} | Type: {{ post.type }} | Category: {{ post.category.name }}
        </div>

        {% if post.image_file %}
        <img alt="Post Image" class="img-fluid rounded shadow-lg mx-auto d-block mb-3 mt-4" src="{{ url_for('static', filename='images/' + post.image_file) }}" style="max-width: 100%;">
        {% endif %}

        <div class="card-text mt-4">
            {% for paragraph in post.text.split('\n') %}
                <p>{{ paragraph }}</p>
            {% endfor %}
        </div>
    </div>
</div>
<br>
<br>
{% endblock %}